# fly.toml app configuration file generated for advent-calendar on 2023-12-02T09:13:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "advent-calendar"
primary_region = "arn"

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
